//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteSW.SWJugador {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.servidor_taller2.grupo1.com/", ConfigurationName="SWJugador.JugadorWebService")]
    public interface JugadorWebService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.servidor_taller2.grupo1.com/JugadorWebService/sumarRequest", ReplyAction="http://ws.servidor_taller2.grupo1.com/JugadorWebService/sumarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteSW.SWJugador.sumarResponse sumar(ClienteSW.SWJugador.sumarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.servidor_taller2.grupo1.com/JugadorWebService/sumarRequest", ReplyAction="http://ws.servidor_taller2.grupo1.com/JugadorWebService/sumarResponse")]
        System.Threading.Tasks.Task<ClienteSW.SWJugador.sumarResponse> sumarAsync(ClienteSW.SWJugador.sumarRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.servidor_taller2.grupo1.com/JugadorWebService/insertarJugadorRequest", ReplyAction="http://ws.servidor_taller2.grupo1.com/JugadorWebService/insertarJugadorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteSW.SWJugador.insertarJugadorResponse insertarJugador(ClienteSW.SWJugador.insertarJugadorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.servidor_taller2.grupo1.com/JugadorWebService/insertarJugadorRequest", ReplyAction="http://ws.servidor_taller2.grupo1.com/JugadorWebService/insertarJugadorResponse")]
        System.Threading.Tasks.Task<ClienteSW.SWJugador.insertarJugadorResponse> insertarJugadorAsync(ClienteSW.SWJugador.insertarJugadorRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.servidor_taller2.grupo1.com/JugadorWebService/buscarporIdJugadorRequest" +
            "", ReplyAction="http://ws.servidor_taller2.grupo1.com/JugadorWebService/buscarporIdJugadorRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteSW.SWJugador.buscarporIdJugadorResponse buscarporIdJugador(ClienteSW.SWJugador.buscarporIdJugadorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.servidor_taller2.grupo1.com/JugadorWebService/buscarporIdJugadorRequest" +
            "", ReplyAction="http://ws.servidor_taller2.grupo1.com/JugadorWebService/buscarporIdJugadorRespons" +
            "e")]
        System.Threading.Tasks.Task<ClienteSW.SWJugador.buscarporIdJugadorResponse> buscarporIdJugadorAsync(ClienteSW.SWJugador.buscarporIdJugadorRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.servidor_taller2.grupo1.com/JugadorWebService/listarJugadoresRequest", ReplyAction="http://ws.servidor_taller2.grupo1.com/JugadorWebService/listarJugadoresResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteSW.SWJugador.listarJugadoresResponse listarJugadores(ClienteSW.SWJugador.listarJugadoresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.servidor_taller2.grupo1.com/JugadorWebService/listarJugadoresRequest", ReplyAction="http://ws.servidor_taller2.grupo1.com/JugadorWebService/listarJugadoresResponse")]
        System.Threading.Tasks.Task<ClienteSW.SWJugador.listarJugadoresResponse> listarJugadoresAsync(ClienteSW.SWJugador.listarJugadoresRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.servidor_taller2.grupo1.com/JugadorWebService/actualizarJugadorRequest", ReplyAction="http://ws.servidor_taller2.grupo1.com/JugadorWebService/actualizarJugadorResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteSW.SWJugador.actualizarJugadorResponse actualizarJugador(ClienteSW.SWJugador.actualizarJugadorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.servidor_taller2.grupo1.com/JugadorWebService/actualizarJugadorRequest", ReplyAction="http://ws.servidor_taller2.grupo1.com/JugadorWebService/actualizarJugadorResponse" +
            "")]
        System.Threading.Tasks.Task<ClienteSW.SWJugador.actualizarJugadorResponse> actualizarJugadorAsync(ClienteSW.SWJugador.actualizarJugadorRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.servidor_taller2.grupo1.com/JugadorWebService/eliminarJugadorRequest", ReplyAction="http://ws.servidor_taller2.grupo1.com/JugadorWebService/eliminarJugadorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteSW.SWJugador.eliminarJugadorResponse eliminarJugador(ClienteSW.SWJugador.eliminarJugadorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.servidor_taller2.grupo1.com/JugadorWebService/eliminarJugadorRequest", ReplyAction="http://ws.servidor_taller2.grupo1.com/JugadorWebService/eliminarJugadorResponse")]
        System.Threading.Tasks.Task<ClienteSW.SWJugador.eliminarJugadorResponse> eliminarJugadorAsync(ClienteSW.SWJugador.eliminarJugadorRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sumar", WrapperNamespace="http://ws.servidor_taller2.grupo1.com/", IsWrapped=true)]
    public partial class sumarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.servidor_taller2.grupo1.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Vacio;
        
        public sumarRequest() {
        }
        
        public sumarRequest(int Vacio) {
            this.Vacio = Vacio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sumarResponse", WrapperNamespace="http://ws.servidor_taller2.grupo1.com/", IsWrapped=true)]
    public partial class sumarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.servidor_taller2.grupo1.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public sumarResponse() {
        }
        
        public sumarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.servidor_taller2.grupo1.com/")]
    public partial class jugadorVO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apodoField;
        
        private string contraseñaField;
        
        private string cuentaField;
        
        private string emailField;
        
        private double estadoRegistroField;
        
        private System.DateTime fechaModificacionField;
        
        private bool fechaModificacionFieldSpecified;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apodo {
            get {
                return this.apodoField;
            }
            set {
                this.apodoField = value;
                this.RaisePropertyChanged("apodo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string contraseña {
            get {
                return this.contraseñaField;
            }
            set {
                this.contraseñaField = value;
                this.RaisePropertyChanged("contraseña");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string cuenta {
            get {
                return this.cuentaField;
            }
            set {
                this.cuentaField = value;
                this.RaisePropertyChanged("cuenta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double estadoRegistro {
            get {
                return this.estadoRegistroField;
            }
            set {
                this.estadoRegistroField = value;
                this.RaisePropertyChanged("estadoRegistro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime fechaModificacion {
            get {
                return this.fechaModificacionField;
            }
            set {
                this.fechaModificacionField = value;
                this.RaisePropertyChanged("fechaModificacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaModificacionSpecified {
            get {
                return this.fechaModificacionFieldSpecified;
            }
            set {
                this.fechaModificacionFieldSpecified = value;
                this.RaisePropertyChanged("fechaModificacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarJugador", WrapperNamespace="http://ws.servidor_taller2.grupo1.com/", IsWrapped=true)]
    public partial class insertarJugadorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.servidor_taller2.grupo1.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteSW.SWJugador.jugadorVO JugadorVO;
        
        public insertarJugadorRequest() {
        }
        
        public insertarJugadorRequest(ClienteSW.SWJugador.jugadorVO JugadorVO) {
            this.JugadorVO = JugadorVO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarJugadorResponse", WrapperNamespace="http://ws.servidor_taller2.grupo1.com/", IsWrapped=true)]
    public partial class insertarJugadorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.servidor_taller2.grupo1.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public insertarJugadorResponse() {
        }
        
        public insertarJugadorResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarporIdJugador", WrapperNamespace="http://ws.servidor_taller2.grupo1.com/", IsWrapped=true)]
    public partial class buscarporIdJugadorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.servidor_taller2.grupo1.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string JugadorVO;
        
        public buscarporIdJugadorRequest() {
        }
        
        public buscarporIdJugadorRequest(string JugadorVO) {
            this.JugadorVO = JugadorVO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarporIdJugadorResponse", WrapperNamespace="http://ws.servidor_taller2.grupo1.com/", IsWrapped=true)]
    public partial class buscarporIdJugadorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.servidor_taller2.grupo1.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteSW.SWJugador.jugadorVO @return;
        
        public buscarporIdJugadorResponse() {
        }
        
        public buscarporIdJugadorResponse(ClienteSW.SWJugador.jugadorVO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarJugadores", WrapperNamespace="http://ws.servidor_taller2.grupo1.com/", IsWrapped=true)]
    public partial class listarJugadoresRequest {
        
        public listarJugadoresRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarJugadoresResponse", WrapperNamespace="http://ws.servidor_taller2.grupo1.com/", IsWrapped=true)]
    public partial class listarJugadoresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.servidor_taller2.grupo1.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteSW.SWJugador.jugadorVO[] @return;
        
        public listarJugadoresResponse() {
        }
        
        public listarJugadoresResponse(ClienteSW.SWJugador.jugadorVO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarJugador", WrapperNamespace="http://ws.servidor_taller2.grupo1.com/", IsWrapped=true)]
    public partial class actualizarJugadorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.servidor_taller2.grupo1.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteSW.SWJugador.jugadorVO JugadorVO;
        
        public actualizarJugadorRequest() {
        }
        
        public actualizarJugadorRequest(ClienteSW.SWJugador.jugadorVO JugadorVO) {
            this.JugadorVO = JugadorVO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarJugadorResponse", WrapperNamespace="http://ws.servidor_taller2.grupo1.com/", IsWrapped=true)]
    public partial class actualizarJugadorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.servidor_taller2.grupo1.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public actualizarJugadorResponse() {
        }
        
        public actualizarJugadorResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarJugador", WrapperNamespace="http://ws.servidor_taller2.grupo1.com/", IsWrapped=true)]
    public partial class eliminarJugadorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.servidor_taller2.grupo1.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string JugadorVO;
        
        public eliminarJugadorRequest() {
        }
        
        public eliminarJugadorRequest(string JugadorVO) {
            this.JugadorVO = JugadorVO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarJugadorResponse", WrapperNamespace="http://ws.servidor_taller2.grupo1.com/", IsWrapped=true)]
    public partial class eliminarJugadorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.servidor_taller2.grupo1.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public eliminarJugadorResponse() {
        }
        
        public eliminarJugadorResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface JugadorWebServiceChannel : ClienteSW.SWJugador.JugadorWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JugadorWebServiceClient : System.ServiceModel.ClientBase<ClienteSW.SWJugador.JugadorWebService>, ClienteSW.SWJugador.JugadorWebService {
        
        public JugadorWebServiceClient() {
        }
        
        public JugadorWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JugadorWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JugadorWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JugadorWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSW.SWJugador.sumarResponse ClienteSW.SWJugador.JugadorWebService.sumar(ClienteSW.SWJugador.sumarRequest request) {
            return base.Channel.sumar(request);
        }
        
        public int sumar(int Vacio) {
            ClienteSW.SWJugador.sumarRequest inValue = new ClienteSW.SWJugador.sumarRequest();
            inValue.Vacio = Vacio;
            ClienteSW.SWJugador.sumarResponse retVal = ((ClienteSW.SWJugador.JugadorWebService)(this)).sumar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSW.SWJugador.sumarResponse> ClienteSW.SWJugador.JugadorWebService.sumarAsync(ClienteSW.SWJugador.sumarRequest request) {
            return base.Channel.sumarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSW.SWJugador.sumarResponse> sumarAsync(int Vacio) {
            ClienteSW.SWJugador.sumarRequest inValue = new ClienteSW.SWJugador.sumarRequest();
            inValue.Vacio = Vacio;
            return ((ClienteSW.SWJugador.JugadorWebService)(this)).sumarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSW.SWJugador.insertarJugadorResponse ClienteSW.SWJugador.JugadorWebService.insertarJugador(ClienteSW.SWJugador.insertarJugadorRequest request) {
            return base.Channel.insertarJugador(request);
        }
        
        public bool insertarJugador(ClienteSW.SWJugador.jugadorVO JugadorVO) {
            ClienteSW.SWJugador.insertarJugadorRequest inValue = new ClienteSW.SWJugador.insertarJugadorRequest();
            inValue.JugadorVO = JugadorVO;
            ClienteSW.SWJugador.insertarJugadorResponse retVal = ((ClienteSW.SWJugador.JugadorWebService)(this)).insertarJugador(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSW.SWJugador.insertarJugadorResponse> ClienteSW.SWJugador.JugadorWebService.insertarJugadorAsync(ClienteSW.SWJugador.insertarJugadorRequest request) {
            return base.Channel.insertarJugadorAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSW.SWJugador.insertarJugadorResponse> insertarJugadorAsync(ClienteSW.SWJugador.jugadorVO JugadorVO) {
            ClienteSW.SWJugador.insertarJugadorRequest inValue = new ClienteSW.SWJugador.insertarJugadorRequest();
            inValue.JugadorVO = JugadorVO;
            return ((ClienteSW.SWJugador.JugadorWebService)(this)).insertarJugadorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSW.SWJugador.buscarporIdJugadorResponse ClienteSW.SWJugador.JugadorWebService.buscarporIdJugador(ClienteSW.SWJugador.buscarporIdJugadorRequest request) {
            return base.Channel.buscarporIdJugador(request);
        }
        
        public ClienteSW.SWJugador.jugadorVO buscarporIdJugador(string JugadorVO) {
            ClienteSW.SWJugador.buscarporIdJugadorRequest inValue = new ClienteSW.SWJugador.buscarporIdJugadorRequest();
            inValue.JugadorVO = JugadorVO;
            ClienteSW.SWJugador.buscarporIdJugadorResponse retVal = ((ClienteSW.SWJugador.JugadorWebService)(this)).buscarporIdJugador(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSW.SWJugador.buscarporIdJugadorResponse> ClienteSW.SWJugador.JugadorWebService.buscarporIdJugadorAsync(ClienteSW.SWJugador.buscarporIdJugadorRequest request) {
            return base.Channel.buscarporIdJugadorAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSW.SWJugador.buscarporIdJugadorResponse> buscarporIdJugadorAsync(string JugadorVO) {
            ClienteSW.SWJugador.buscarporIdJugadorRequest inValue = new ClienteSW.SWJugador.buscarporIdJugadorRequest();
            inValue.JugadorVO = JugadorVO;
            return ((ClienteSW.SWJugador.JugadorWebService)(this)).buscarporIdJugadorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSW.SWJugador.listarJugadoresResponse ClienteSW.SWJugador.JugadorWebService.listarJugadores(ClienteSW.SWJugador.listarJugadoresRequest request) {
            return base.Channel.listarJugadores(request);
        }
        
        public ClienteSW.SWJugador.jugadorVO[] listarJugadores() {
            ClienteSW.SWJugador.listarJugadoresRequest inValue = new ClienteSW.SWJugador.listarJugadoresRequest();
            ClienteSW.SWJugador.listarJugadoresResponse retVal = ((ClienteSW.SWJugador.JugadorWebService)(this)).listarJugadores(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSW.SWJugador.listarJugadoresResponse> ClienteSW.SWJugador.JugadorWebService.listarJugadoresAsync(ClienteSW.SWJugador.listarJugadoresRequest request) {
            return base.Channel.listarJugadoresAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSW.SWJugador.listarJugadoresResponse> listarJugadoresAsync() {
            ClienteSW.SWJugador.listarJugadoresRequest inValue = new ClienteSW.SWJugador.listarJugadoresRequest();
            return ((ClienteSW.SWJugador.JugadorWebService)(this)).listarJugadoresAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSW.SWJugador.actualizarJugadorResponse ClienteSW.SWJugador.JugadorWebService.actualizarJugador(ClienteSW.SWJugador.actualizarJugadorRequest request) {
            return base.Channel.actualizarJugador(request);
        }
        
        public bool actualizarJugador(ClienteSW.SWJugador.jugadorVO JugadorVO) {
            ClienteSW.SWJugador.actualizarJugadorRequest inValue = new ClienteSW.SWJugador.actualizarJugadorRequest();
            inValue.JugadorVO = JugadorVO;
            ClienteSW.SWJugador.actualizarJugadorResponse retVal = ((ClienteSW.SWJugador.JugadorWebService)(this)).actualizarJugador(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSW.SWJugador.actualizarJugadorResponse> ClienteSW.SWJugador.JugadorWebService.actualizarJugadorAsync(ClienteSW.SWJugador.actualizarJugadorRequest request) {
            return base.Channel.actualizarJugadorAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSW.SWJugador.actualizarJugadorResponse> actualizarJugadorAsync(ClienteSW.SWJugador.jugadorVO JugadorVO) {
            ClienteSW.SWJugador.actualizarJugadorRequest inValue = new ClienteSW.SWJugador.actualizarJugadorRequest();
            inValue.JugadorVO = JugadorVO;
            return ((ClienteSW.SWJugador.JugadorWebService)(this)).actualizarJugadorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSW.SWJugador.eliminarJugadorResponse ClienteSW.SWJugador.JugadorWebService.eliminarJugador(ClienteSW.SWJugador.eliminarJugadorRequest request) {
            return base.Channel.eliminarJugador(request);
        }
        
        public bool eliminarJugador(string JugadorVO) {
            ClienteSW.SWJugador.eliminarJugadorRequest inValue = new ClienteSW.SWJugador.eliminarJugadorRequest();
            inValue.JugadorVO = JugadorVO;
            ClienteSW.SWJugador.eliminarJugadorResponse retVal = ((ClienteSW.SWJugador.JugadorWebService)(this)).eliminarJugador(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSW.SWJugador.eliminarJugadorResponse> ClienteSW.SWJugador.JugadorWebService.eliminarJugadorAsync(ClienteSW.SWJugador.eliminarJugadorRequest request) {
            return base.Channel.eliminarJugadorAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSW.SWJugador.eliminarJugadorResponse> eliminarJugadorAsync(string JugadorVO) {
            ClienteSW.SWJugador.eliminarJugadorRequest inValue = new ClienteSW.SWJugador.eliminarJugadorRequest();
            inValue.JugadorVO = JugadorVO;
            return ((ClienteSW.SWJugador.JugadorWebService)(this)).eliminarJugadorAsync(inValue);
        }
    }
}
