//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteSW.SWEspecie {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.servidor_taller2.grupo1.com/", ConfigurationName="SWEspecie.EspecieWebService")]
    public interface EspecieWebService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.servidor_taller2.grupo1.com/EspecieWebService/listarEspeciesRequest", ReplyAction="http://ws.servidor_taller2.grupo1.com/EspecieWebService/listarEspeciesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteSW.SWEspecie.listarEspeciesResponse listarEspecies(ClienteSW.SWEspecie.listarEspeciesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.servidor_taller2.grupo1.com/EspecieWebService/listarEspeciesRequest", ReplyAction="http://ws.servidor_taller2.grupo1.com/EspecieWebService/listarEspeciesResponse")]
        System.Threading.Tasks.Task<ClienteSW.SWEspecie.listarEspeciesResponse> listarEspeciesAsync(ClienteSW.SWEspecie.listarEspeciesRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.servidor_taller2.grupo1.com/EspecieWebService/actualizarEspecieRequest", ReplyAction="http://ws.servidor_taller2.grupo1.com/EspecieWebService/actualizarEspecieResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteSW.SWEspecie.actualizarEspecieResponse actualizarEspecie(ClienteSW.SWEspecie.actualizarEspecieRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.servidor_taller2.grupo1.com/EspecieWebService/actualizarEspecieRequest", ReplyAction="http://ws.servidor_taller2.grupo1.com/EspecieWebService/actualizarEspecieResponse" +
            "")]
        System.Threading.Tasks.Task<ClienteSW.SWEspecie.actualizarEspecieResponse> actualizarEspecieAsync(ClienteSW.SWEspecie.actualizarEspecieRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.servidor_taller2.grupo1.com/EspecieWebService/eliminarEspecieRequest", ReplyAction="http://ws.servidor_taller2.grupo1.com/EspecieWebService/eliminarEspecieResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteSW.SWEspecie.eliminarEspecieResponse eliminarEspecie(ClienteSW.SWEspecie.eliminarEspecieRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.servidor_taller2.grupo1.com/EspecieWebService/eliminarEspecieRequest", ReplyAction="http://ws.servidor_taller2.grupo1.com/EspecieWebService/eliminarEspecieResponse")]
        System.Threading.Tasks.Task<ClienteSW.SWEspecie.eliminarEspecieResponse> eliminarEspecieAsync(ClienteSW.SWEspecie.eliminarEspecieRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.servidor_taller2.grupo1.com/EspecieWebService/insertarEspecieRequest", ReplyAction="http://ws.servidor_taller2.grupo1.com/EspecieWebService/insertarEspecieResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteSW.SWEspecie.insertarEspecieResponse insertarEspecie(ClienteSW.SWEspecie.insertarEspecieRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.servidor_taller2.grupo1.com/EspecieWebService/insertarEspecieRequest", ReplyAction="http://ws.servidor_taller2.grupo1.com/EspecieWebService/insertarEspecieResponse")]
        System.Threading.Tasks.Task<ClienteSW.SWEspecie.insertarEspecieResponse> insertarEspecieAsync(ClienteSW.SWEspecie.insertarEspecieRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.servidor_taller2.grupo1.com/EspecieWebService/buscarporIdEspecieRequest" +
            "", ReplyAction="http://ws.servidor_taller2.grupo1.com/EspecieWebService/buscarporIdEspecieRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteSW.SWEspecie.buscarporIdEspecieResponse buscarporIdEspecie(ClienteSW.SWEspecie.buscarporIdEspecieRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.servidor_taller2.grupo1.com/EspecieWebService/buscarporIdEspecieRequest" +
            "", ReplyAction="http://ws.servidor_taller2.grupo1.com/EspecieWebService/buscarporIdEspecieRespons" +
            "e")]
        System.Threading.Tasks.Task<ClienteSW.SWEspecie.buscarporIdEspecieResponse> buscarporIdEspecieAsync(ClienteSW.SWEspecie.buscarporIdEspecieRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.servidor_taller2.grupo1.com/")]
    public partial class especieVO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double estadoRegistroField;
        
        private System.DateTime fechaModificacionField;
        
        private bool fechaModificacionFieldSpecified;
        
        private string idField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double estadoRegistro {
            get {
                return this.estadoRegistroField;
            }
            set {
                this.estadoRegistroField = value;
                this.RaisePropertyChanged("estadoRegistro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fechaModificacion {
            get {
                return this.fechaModificacionField;
            }
            set {
                this.fechaModificacionField = value;
                this.RaisePropertyChanged("fechaModificacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaModificacionSpecified {
            get {
                return this.fechaModificacionFieldSpecified;
            }
            set {
                this.fechaModificacionFieldSpecified = value;
                this.RaisePropertyChanged("fechaModificacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEspecies", WrapperNamespace="http://ws.servidor_taller2.grupo1.com/", IsWrapped=true)]
    public partial class listarEspeciesRequest {
        
        public listarEspeciesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEspeciesResponse", WrapperNamespace="http://ws.servidor_taller2.grupo1.com/", IsWrapped=true)]
    public partial class listarEspeciesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.servidor_taller2.grupo1.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteSW.SWEspecie.especieVO[] @return;
        
        public listarEspeciesResponse() {
        }
        
        public listarEspeciesResponse(ClienteSW.SWEspecie.especieVO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarEspecie", WrapperNamespace="http://ws.servidor_taller2.grupo1.com/", IsWrapped=true)]
    public partial class actualizarEspecieRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.servidor_taller2.grupo1.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteSW.SWEspecie.especieVO EspecieVO;
        
        public actualizarEspecieRequest() {
        }
        
        public actualizarEspecieRequest(ClienteSW.SWEspecie.especieVO EspecieVO) {
            this.EspecieVO = EspecieVO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarEspecieResponse", WrapperNamespace="http://ws.servidor_taller2.grupo1.com/", IsWrapped=true)]
    public partial class actualizarEspecieResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.servidor_taller2.grupo1.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public actualizarEspecieResponse() {
        }
        
        public actualizarEspecieResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarEspecie", WrapperNamespace="http://ws.servidor_taller2.grupo1.com/", IsWrapped=true)]
    public partial class eliminarEspecieRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.servidor_taller2.grupo1.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EspecieVO;
        
        public eliminarEspecieRequest() {
        }
        
        public eliminarEspecieRequest(string EspecieVO) {
            this.EspecieVO = EspecieVO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarEspecieResponse", WrapperNamespace="http://ws.servidor_taller2.grupo1.com/", IsWrapped=true)]
    public partial class eliminarEspecieResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.servidor_taller2.grupo1.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public eliminarEspecieResponse() {
        }
        
        public eliminarEspecieResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarEspecie", WrapperNamespace="http://ws.servidor_taller2.grupo1.com/", IsWrapped=true)]
    public partial class insertarEspecieRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.servidor_taller2.grupo1.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteSW.SWEspecie.especieVO EspecieVO;
        
        public insertarEspecieRequest() {
        }
        
        public insertarEspecieRequest(ClienteSW.SWEspecie.especieVO EspecieVO) {
            this.EspecieVO = EspecieVO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarEspecieResponse", WrapperNamespace="http://ws.servidor_taller2.grupo1.com/", IsWrapped=true)]
    public partial class insertarEspecieResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.servidor_taller2.grupo1.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public insertarEspecieResponse() {
        }
        
        public insertarEspecieResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarporIdEspecie", WrapperNamespace="http://ws.servidor_taller2.grupo1.com/", IsWrapped=true)]
    public partial class buscarporIdEspecieRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.servidor_taller2.grupo1.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EspecieVO;
        
        public buscarporIdEspecieRequest() {
        }
        
        public buscarporIdEspecieRequest(string EspecieVO) {
            this.EspecieVO = EspecieVO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarporIdEspecieResponse", WrapperNamespace="http://ws.servidor_taller2.grupo1.com/", IsWrapped=true)]
    public partial class buscarporIdEspecieResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.servidor_taller2.grupo1.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteSW.SWEspecie.especieVO @return;
        
        public buscarporIdEspecieResponse() {
        }
        
        public buscarporIdEspecieResponse(ClienteSW.SWEspecie.especieVO @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EspecieWebServiceChannel : ClienteSW.SWEspecie.EspecieWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EspecieWebServiceClient : System.ServiceModel.ClientBase<ClienteSW.SWEspecie.EspecieWebService>, ClienteSW.SWEspecie.EspecieWebService {
        
        public EspecieWebServiceClient() {
        }
        
        public EspecieWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EspecieWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EspecieWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EspecieWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSW.SWEspecie.listarEspeciesResponse ClienteSW.SWEspecie.EspecieWebService.listarEspecies(ClienteSW.SWEspecie.listarEspeciesRequest request) {
            return base.Channel.listarEspecies(request);
        }
        
        public ClienteSW.SWEspecie.especieVO[] listarEspecies() {
            ClienteSW.SWEspecie.listarEspeciesRequest inValue = new ClienteSW.SWEspecie.listarEspeciesRequest();
            ClienteSW.SWEspecie.listarEspeciesResponse retVal = ((ClienteSW.SWEspecie.EspecieWebService)(this)).listarEspecies(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSW.SWEspecie.listarEspeciesResponse> ClienteSW.SWEspecie.EspecieWebService.listarEspeciesAsync(ClienteSW.SWEspecie.listarEspeciesRequest request) {
            return base.Channel.listarEspeciesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSW.SWEspecie.listarEspeciesResponse> listarEspeciesAsync() {
            ClienteSW.SWEspecie.listarEspeciesRequest inValue = new ClienteSW.SWEspecie.listarEspeciesRequest();
            return ((ClienteSW.SWEspecie.EspecieWebService)(this)).listarEspeciesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSW.SWEspecie.actualizarEspecieResponse ClienteSW.SWEspecie.EspecieWebService.actualizarEspecie(ClienteSW.SWEspecie.actualizarEspecieRequest request) {
            return base.Channel.actualizarEspecie(request);
        }
        
        public bool actualizarEspecie(ClienteSW.SWEspecie.especieVO EspecieVO) {
            ClienteSW.SWEspecie.actualizarEspecieRequest inValue = new ClienteSW.SWEspecie.actualizarEspecieRequest();
            inValue.EspecieVO = EspecieVO;
            ClienteSW.SWEspecie.actualizarEspecieResponse retVal = ((ClienteSW.SWEspecie.EspecieWebService)(this)).actualizarEspecie(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSW.SWEspecie.actualizarEspecieResponse> ClienteSW.SWEspecie.EspecieWebService.actualizarEspecieAsync(ClienteSW.SWEspecie.actualizarEspecieRequest request) {
            return base.Channel.actualizarEspecieAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSW.SWEspecie.actualizarEspecieResponse> actualizarEspecieAsync(ClienteSW.SWEspecie.especieVO EspecieVO) {
            ClienteSW.SWEspecie.actualizarEspecieRequest inValue = new ClienteSW.SWEspecie.actualizarEspecieRequest();
            inValue.EspecieVO = EspecieVO;
            return ((ClienteSW.SWEspecie.EspecieWebService)(this)).actualizarEspecieAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSW.SWEspecie.eliminarEspecieResponse ClienteSW.SWEspecie.EspecieWebService.eliminarEspecie(ClienteSW.SWEspecie.eliminarEspecieRequest request) {
            return base.Channel.eliminarEspecie(request);
        }
        
        public bool eliminarEspecie(string EspecieVO) {
            ClienteSW.SWEspecie.eliminarEspecieRequest inValue = new ClienteSW.SWEspecie.eliminarEspecieRequest();
            inValue.EspecieVO = EspecieVO;
            ClienteSW.SWEspecie.eliminarEspecieResponse retVal = ((ClienteSW.SWEspecie.EspecieWebService)(this)).eliminarEspecie(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSW.SWEspecie.eliminarEspecieResponse> ClienteSW.SWEspecie.EspecieWebService.eliminarEspecieAsync(ClienteSW.SWEspecie.eliminarEspecieRequest request) {
            return base.Channel.eliminarEspecieAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSW.SWEspecie.eliminarEspecieResponse> eliminarEspecieAsync(string EspecieVO) {
            ClienteSW.SWEspecie.eliminarEspecieRequest inValue = new ClienteSW.SWEspecie.eliminarEspecieRequest();
            inValue.EspecieVO = EspecieVO;
            return ((ClienteSW.SWEspecie.EspecieWebService)(this)).eliminarEspecieAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSW.SWEspecie.insertarEspecieResponse ClienteSW.SWEspecie.EspecieWebService.insertarEspecie(ClienteSW.SWEspecie.insertarEspecieRequest request) {
            return base.Channel.insertarEspecie(request);
        }
        
        public bool insertarEspecie(ClienteSW.SWEspecie.especieVO EspecieVO) {
            ClienteSW.SWEspecie.insertarEspecieRequest inValue = new ClienteSW.SWEspecie.insertarEspecieRequest();
            inValue.EspecieVO = EspecieVO;
            ClienteSW.SWEspecie.insertarEspecieResponse retVal = ((ClienteSW.SWEspecie.EspecieWebService)(this)).insertarEspecie(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSW.SWEspecie.insertarEspecieResponse> ClienteSW.SWEspecie.EspecieWebService.insertarEspecieAsync(ClienteSW.SWEspecie.insertarEspecieRequest request) {
            return base.Channel.insertarEspecieAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSW.SWEspecie.insertarEspecieResponse> insertarEspecieAsync(ClienteSW.SWEspecie.especieVO EspecieVO) {
            ClienteSW.SWEspecie.insertarEspecieRequest inValue = new ClienteSW.SWEspecie.insertarEspecieRequest();
            inValue.EspecieVO = EspecieVO;
            return ((ClienteSW.SWEspecie.EspecieWebService)(this)).insertarEspecieAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSW.SWEspecie.buscarporIdEspecieResponse ClienteSW.SWEspecie.EspecieWebService.buscarporIdEspecie(ClienteSW.SWEspecie.buscarporIdEspecieRequest request) {
            return base.Channel.buscarporIdEspecie(request);
        }
        
        public ClienteSW.SWEspecie.especieVO buscarporIdEspecie(string EspecieVO) {
            ClienteSW.SWEspecie.buscarporIdEspecieRequest inValue = new ClienteSW.SWEspecie.buscarporIdEspecieRequest();
            inValue.EspecieVO = EspecieVO;
            ClienteSW.SWEspecie.buscarporIdEspecieResponse retVal = ((ClienteSW.SWEspecie.EspecieWebService)(this)).buscarporIdEspecie(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSW.SWEspecie.buscarporIdEspecieResponse> ClienteSW.SWEspecie.EspecieWebService.buscarporIdEspecieAsync(ClienteSW.SWEspecie.buscarporIdEspecieRequest request) {
            return base.Channel.buscarporIdEspecieAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSW.SWEspecie.buscarporIdEspecieResponse> buscarporIdEspecieAsync(string EspecieVO) {
            ClienteSW.SWEspecie.buscarporIdEspecieRequest inValue = new ClienteSW.SWEspecie.buscarporIdEspecieRequest();
            inValue.EspecieVO = EspecieVO;
            return ((ClienteSW.SWEspecie.EspecieWebService)(this)).buscarporIdEspecieAsync(inValue);
        }
    }
}
